### ISSUE TITLE
Cannot use more than 1 reporter with testcafe 1.0

### ISSUE THREAD

**Issue by FamiliprixEtienneLab** [DevExpress/gulp-testcafe#10]
Usage:
testcafe({reporter: ["spec", { "name": "xunit", "file": "TestResult.xml"}]})

Error message:
You cannot call the "reporter" method more than once. Pass an array of parameters to this method instead.

Code to blame:
https://github.com/DevExpress/gulp-testcafe/blob/master/index.js#L68

**Comment by miherlosev** [comment]
Thank you for the detailed description. It's a bug and I will fix it right now

**Comment by FamiliprixEtienneLab** [comment]
This is fixed now. Thanks!
Just wanted to add that you cannot use the sample configuration I included as is because both reporters try to write to stdout. Here is a better version:
```
const gulp = require('gulp');
const testcafe = require('gulp-testcafe');
const fs = require('fs');
gulp.task('run-testcafe-tests', () => {
    return gulp
        .src('./Tests/**/*.ts')
        .pipe(
            testcafe({ 
                browsers: ['chrome:headless'], 
                reporter: [
                    "spec",
                    { 
                        "name": "xunit", 
                        "output": fs.createWriteStream("TestResult.xml")
                    }
                ]
            })
        );
});
```
