### ISSUE TITLE
`testcafe` should be a peerDependency

### ISSUE THREAD

**Issue by justrhysism** [DevExpress/gulp-testcafe#13]
`gulp-testcafe` shouldn't dictate which version of `testcafe` to use, but support a maximum range of `testcafe` versions.

Gulp and Testcafe should be **peerDependencies**.

For more information on, please see: https://medium.com/@jacob.h.page/common-npm-mistakes-51bf8989079f#d2fe

**Comment by miherlosev** [comment]
Hi @justrhysism
> Gulp and Testcafe should be peerDependencies.

Yes, you are right. Thank you for this remark.
