### ISSUE TITLE
gulp-testcafe doesn't work

### ISSUE THREAD

**Issue by dabeng** [DevExpress/gulp-testcafe#14]
Message:
    The concurrency factor should be an integer greater or equal to 1.
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

**Comment by dabeng** [comment]
code snippets of my package.json
```js
  "devDependencies": {
    "gulp": "^4.0.2",
    "gulp-testcafe": "^1.0.0",
    "testcafe": "^1.5.0"
  }
```

**Comment by AndreyBelym** [comment]
Thank you for your report, I've reproduced the problem. We will fix it and provide a new release in a few days.

**Comment by dabeng** [comment]
@AndreyBelym Thanks a lot 😊

**Comment by Farfurix** [comment]
@dabeng 

Hello,

We have fixed the issue in this [PR](https://github.com/DevExpress/gulp-testcafe/pull/15). Please update your `gulp-testcafe` to the latest `v1.0.1` version.
