### ISSUE TITLE
Is it possible to pass in all testcafe command line options?

### ISSUE THREAD

**Issue by danielabar** [DevExpress/gulp-testcafe#5]
There seem to be a lot more testcafe [command line options](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html) then the list of options listed in this plugin's readme.

For example, setting screenshot path, concurrency, debug mode etc.

Is it possible to pass in any/all of testcafe command line options using this plugin?

**Comment by AndreyBelym** [comment]
Hi @danielabar, I'm updating TestCafe version in this package right now. After that, all new features will be available in `gulp-testcafe`.

**Comment by AndreyBelym** [comment]
But you can set a path to a screenshots folder right now, check https://github.com/DevExpress/gulp-testcafe#screenshotspath.

**Comment by danielabar** [comment]
Just tried it out using some of the new options `app`, `appInitDelay` and `concurrency` and it's working well. Thanks!

**Comment by HenrrySalinasJala** [comment]
@AndreyBelym I see it is not possible to specify pathPattern  for the screenshots: 

```javascript
    function onStreamEnd (cb) {
        var stream   = this;
        var testcafe = null;

        createTestCafe(opts.hostname, opts.ports[0], opts.ports[1])
            .then(function (tc) {
                testcafe = tc;

                var runner = testcafe.createRunner();
runner
                    .src(files)
                    .browsers(opts.browsers)
                    .filter(opts.filter)
                    .screenshots(opts.screenshotsPath, opts.takeScreenshotsOnFail) // only the first two parameters are sent
                    .reporter(opts.reporter);
```
how can I send `pathPattern` parameter through gulp-testcafe

**Comment by SergeyShurygin** [comment]
We created an issue https://github.com/DevExpress/gulp-testcafe/issues/17  to support all screenshot options.  Let move further discussion into it.   Your PRs are welcome too.
